<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/coco-starterkit/init/class/core/init.php';
require_once 'config.php';

class statusTracker extends config
{
    public $id;

    public function __construct($id = null)
    {
        $this->id = $id;
    }

    public function statusCOG()
    {
        switch ($this->id) {
            case 1:
                echo '';
                echo '<div class="tl tl mt-4">';
                echo '';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6>';
                echo '<h5 class="page-title text-dark" id="submitted"></h5>';
                echo '<p id="submitteddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6>';
                echo '<h5 class="page-title text-dark" id="verified"></h5>';
                echo '<p id="verifieddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Registrar</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 2:
                echo '';
                echo '<div class="tl tl mt-4">';
                echo '';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6>';
                echo '<h5 class="page-title text-dark" id="submitted"></h5>';
                echo '<p id="submitteddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6>';
                echo '<h5 class="page-title text-dark" id="verified"></h5>';
                echo '<p id="verifieddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6>';
                echo '<h5 class="page-title text-dark" id="approved"></h5>';
                echo '<p id="approveddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Student Records Assistant <br>in-charge</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 3:
                echo '';
                echo '<div class="tl tl mt-4">';
                echo '';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6>';
                echo '<h5 class="page-title text-dark" id="submitted"></h5>';
                echo '<p id="submitteddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6>';
                echo '<h5 class="page-title text-dark" id="verified"></h5>';
                echo '<p id="verifieddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6>';
                echo '<h5 class="page-title text-dark" id="approved"></h5>';
                echo '<p id="approveddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-green"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Attested By</h6>';
                echo '<h5 class="page-title text-dark" id="attested"></h5>';
                echo '<p id="attesteddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
        }
    }

    public function statusCOGP()
    {
        switch ($this->id) {
            case 1:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted2"></h5>';
                echo '<p id="submitteddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended2"></h5>';
                echo '<p id="recommendeddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Student Records Assistant <br>in-charge</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
           
                break;
            case 2:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted2"></h5>';
                echo '<p id="submitteddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended2"></h5>';
                echo '<p id="recommendeddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6> <h5 class="page-title text-dark" id="verified2"></h5>';
                echo '<p id="verifieddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Registrar</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 3:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted2"></h5>';
                echo '<p id="submitteddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended2"></h5>';
                echo '<p id="recommendeddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6> <h5 class="page-title text-dark" id="verified2"></h5>';
                echo '<p id="verifieddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved2"></h5>';
                echo '<p id="approveddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Student Records Assistant <br>in-charge</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 4:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted2"></h5>';
                echo '<p id="submitteddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended2"></h5>';
                echo '<p id="recommendeddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6> <h5 class="page-title text-dark" id="verified2"></h5>';
                echo '<p id="verifieddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved2"></h5>';
                echo '<p id="approveddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '';
                echo '';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-green"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Attested By</h6> <h5 class="page-title text-dark" id="attested2"></h5>';
                echo '<p id="attesteddate2"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '';
                echo '</div>';
                break;
        }
    }

    public function statusCCG()
    {
        switch ($this->id) {
            case 1:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted3"></h5>';
                echo '<p id="submitteddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended"></h5>';
                echo '<p id="recommendeddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for VP for Academic Affairs</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 2:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted3"></h5>';
                echo '<p id="submitteddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended"></h5>';
                echo '<p id="recommendeddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved3"></h5>';
                echo '<p id="approveddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Registrar</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 3:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted3"></h5>';
                echo '<p id="submitteddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended"></h5>';
                echo '<p id="recommendeddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved3"></h5>';
                echo '<p id="approveddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved  for Encoding by</h6> <h5 class="page-title text-dark" id="approvedforencode"></h5>';
                echo '<p id="approvedforencodedate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Student Records Assistant <br>in-charge</h6>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                break;
            case 4:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted3"></h5>';
                echo '<p id="submitteddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended"></h5>';
                echo '<p id="recommendeddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved3"></h5>';
                echo '<p id="approveddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved  for Encoding by</h6> <h5 class="page-title text-dark" id="approvedforencode"></h5>';
                echo '<p id="approvedforencodedate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6> <h5 class="page-title text-dark" id="verified"></h5>';
                echo '<p id="verifieddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-gray"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Waiting for Student Records Assistant <br>in-charge</h6>';
                echo '</div>';
                echo '';
                echo '</div>';
                break;
            case 5:
                echo '<div class="tl tl mt-4">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Submitted By</h6> <h5 class="page-title text-dark" id="submitted3"></h5>';
                echo '<p id="submitteddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Recommended By</h6> <h5 class="page-title text-dark" id="recommended"></h5>';
                echo '<p id="recommendeddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved By</h6> <h5 class="page-title text-dark" id="approved3"></h5>';
                echo '<p id="approveddate3"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Approved  for Encoding by</h6> <h5 class="page-title text-dark" id="approvedforencode"></h5>';
                echo '<p id="approvedforencodedate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl tl">';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-secondary"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Verified By</h6> <h5 class="page-title text-dark" id="verified"></h5>';
                echo '<p id="verifieddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '<div class="tl-item tl-element">';
                echo '<div>';
                echo '<span class="tl-icon bounce-in">';
                echo '<i class="tl-badge badge-dot badge-dot-xl badge-green"> </i>';
                echo '</span>';
                echo '<div class="tl-content bounce-in">';
                echo '<h6 class="page-title text-dark font-weight-medium">Attested By</h6> <h5 class="page-title text-dark" id="attested"></h5>';
                echo '<p id="attesteddate"></p>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '';
                echo '</div>';
                break;
        }
    }
}
